name: CI Workflow

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.TEST_1 }}  

    strategy:
      matrix:
        node-version: [16.x] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          always-auth: false
          check-latest: false
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      - name: Install dependencies
        run: npm install  # Use 'yarn install' if you prefer Yarn

   
      - name: Run tests with API key
        run: npm test --apiKey=${{ env.TEST_1 }}
