name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          always-auth: false
          check-latest: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
